version: "3.8"
services:
  redis:
    image: redis:6.2-alpine
    restart: always
    ports:
      - "6379:6379"
    command: >
      --requirepass testpass
      --port 6379
    volumes:
      - cache_vol:/data

volumes:
  cache_vol:
